<?php

return [
    'roles' => [
        'super_admin' => [
            'clients' => ['view' => true, 'create' => true, 'edit' => true, 'delete' => true, 'validate' => true, 'export' => true],
            'prescriptions' => ['view' => true, 'create' => true, 'edit' => true, 'delete' => true, 'validate' => true, 'export' => true],
            'ventes' => ['view' => true, 'create' => true, 'edit' => true, 'delete' => true, 'validate' => true, 'export' => true],
            'factures' => ['view' => true, 'create' => true, 'edit' => true, 'delete' => true, 'validate' => true, 'export' => true],
            'paiements' => ['view' => true, 'create' => true, 'edit' => true, 'delete' => true, 'validate' => true, 'export' => true],
            'stock' => ['view' => true, 'create' => true, 'edit' => true, 'delete' => true, 'validate' => true, 'export' => true],
            'fournisseurs' => ['view' => true, 'create' => true, 'edit' => true, 'delete' => true, 'validate' => true, 'export' => true],
            'bons_commande' => ['view' => true, 'create' => true, 'edit' => true, 'delete' => true, 'validate' => true, 'export' => true],
            'bons_livraison' => ['view' => true, 'create' => true, 'edit' => true, 'delete' => true, 'validate' => true, 'export' => true],
            'atelier' => ['view' => true, 'create' => true, 'edit' => true, 'delete' => true, 'validate' => true, 'export' => true],
            'rapports' => ['view' => true, 'create' => true, 'edit' => true, 'delete' => true, 'validate' => true, 'export' => true],
            'parametres' => ['view' => true, 'create' => true, 'edit' => true, 'delete' => true, 'validate' => true, 'export' => true],
            'utilisateurs' => ['view' => true, 'create' => true, 'edit' => true, 'delete' => true, 'validate' => true, 'export' => true],
            'abonnement' => ['view' => true, 'create' => true, 'edit' => true, 'delete' => true, 'validate' => true, 'export' => true],
        ],
        'admin' => [
            'clients' => ['view' => true, 'create' => true, 'edit' => true, 'delete' => true, 'validate' => true, 'export' => true],
            'prescriptions' => ['view' => true, 'create' => true, 'edit' => true, 'delete' => true, 'validate' => true, 'export' => true],
            'ventes' => ['view' => true, 'create' => true, 'edit' => true, 'delete' => true, 'validate' => true, 'export' => true],
            'factures' => ['view' => true, 'create' => true, 'edit' => true, 'delete' => true, 'validate' => true, 'export' => true],
            'paiements' => ['view' => true, 'create' => true, 'edit' => true, 'delete' => true, 'validate' => true, 'export' => true],
            'stock' => ['view' => true, 'create' => true, 'edit' => true, 'delete' => true, 'validate' => true, 'export' => true],
            'fournisseurs' => ['view' => true, 'create' => true, 'edit' => true, 'delete' => true, 'validate' => true, 'export' => true],
            'bons_commande' => ['view' => true, 'create' => true, 'edit' => true, 'delete' => true, 'validate' => true, 'export' => true],
            'bons_livraison' => ['view' => true, 'create' => true, 'edit' => true, 'delete' => true, 'validate' => true, 'export' => true],
            'atelier' => ['view' => true, 'create' => true, 'edit' => true, 'delete' => true, 'validate' => true, 'export' => true],
            'rapports' => ['view' => true, 'create' => true, 'edit' => true, 'delete' => true, 'validate' => true, 'export' => true],
            'parametres' => ['view' => true, 'create' => true, 'edit' => true, 'delete' => true, 'validate' => true, 'export' => true],
            'utilisateurs' => ['view' => true, 'create' => true, 'edit' => true, 'delete' => true, 'validate' => true, 'export' => true],
            'abonnement' => ['view' => true, 'create' => false, 'edit' => false, 'delete' => false, 'validate' => false, 'export' => false],
        ],
        'manager' => [
            'clients' => ['view' => true, 'create' => true, 'edit' => true, 'delete' => false, 'validate' => true, 'export' => true],
            'prescriptions' => ['view' => true, 'create' => true, 'edit' => true, 'delete' => false, 'validate' => true, 'export' => true],
            'ventes' => ['view' => true, 'create' => true, 'edit' => true, 'delete' => false, 'validate' => true, 'export' => true],
            'factures' => ['view' => true, 'create' => true, 'edit' => true, 'delete' => false, 'validate' => true, 'export' => true],
            'paiements' => ['view' => true, 'create' => true, 'edit' => true, 'delete' => false, 'validate' => true, 'export' => true],
            'stock' => ['view' => true, 'create' => true, 'edit' => true, 'delete' => false, 'validate' => true, 'export' => true],
            'fournisseurs' => ['view' => true, 'create' => true, 'edit' => true, 'delete' => false, 'validate' => false, 'export' => true],
            'bons_commande' => ['view' => true, 'create' => true, 'edit' => true, 'delete' => false, 'validate' => true, 'export' => true],
            'bons_livraison' => ['view' => true, 'create' => true, 'edit' => true, 'delete' => false, 'validate' => true, 'export' => true],
            'atelier' => ['view' => true, 'create' => true, 'edit' => true, 'delete' => false, 'validate' => true, 'export' => true],
            'rapports' => ['view' => true, 'create' => false, 'edit' => false, 'delete' => false, 'validate' => false, 'export' => true],
            'parametres' => ['view' => true, 'create' => false, 'edit' => false, 'delete' => false, 'validate' => false, 'export' => false],
            'utilisateurs' => ['view' => true, 'create' => false, 'edit' => false, 'delete' => false, 'validate' => false, 'export' => false],
            'abonnement' => ['view' => true, 'create' => true, 'edit' => false, 'delete' => false, 'validate' => false, 'export' => false],
        ],
        'vendeur' => [
            'clients' => ['view' => true, 'create' => true, 'edit' => true, 'delete' => false, 'validate' => false, 'export' => false],
            'prescriptions' => ['view' => true, 'create' => true, 'edit' => true, 'delete' => false, 'validate' => false, 'export' => false],
            'ventes' => ['view' => true, 'create' => true, 'edit' => true, 'delete' => false, 'validate' => false, 'export' => false],
            'factures' => ['view' => true, 'create' => true, 'edit' => false, 'delete' => false, 'validate' => false, 'export' => false],
            'paiements' => ['view' => true, 'create' => true, 'edit' => false, 'delete' => false, 'validate' => false, 'export' => false],
            'stock' => ['view' => true, 'create' => false, 'edit' => false, 'delete' => false, 'validate' => false, 'export' => false],
            'fournisseurs' => ['view' => false, 'create' => false, 'edit' => false, 'delete' => false, 'validate' => false, 'export' => false],
            'bons_commande' => ['view' => false, 'create' => false, 'edit' => false, 'delete' => false, 'validate' => false, 'export' => false],
            'bons_livraison' => ['view' => false, 'create' => false, 'edit' => false, 'delete' => false, 'validate' => false, 'export' => false],
            'atelier' => ['view' => true, 'create' => true, 'edit' => false, 'delete' => false, 'validate' => false, 'export' => false],
            'rapports' => ['view' => false, 'create' => false, 'edit' => false, 'delete' => false, 'validate' => false, 'export' => false],
            'parametres' => ['view' => false, 'create' => false, 'edit' => false, 'delete' => false, 'validate' => false, 'export' => false],
            'utilisateurs' => ['view' => false, 'create' => false, 'edit' => false, 'delete' => false, 'validate' => false, 'export' => false],
            'abonnement' => ['view' => true, 'create' => true, 'edit' => false, 'delete' => false, 'validate' => false, 'export' => false],
        ],
        'technicien' => [
            'clients' => ['view' => true, 'create' => false, 'edit' => false, 'delete' => false, 'validate' => false, 'export' => false],
            'prescriptions' => ['view' => true, 'create' => false, 'edit' => false, 'delete' => false, 'validate' => false, 'export' => false],
            'ventes' => ['view' => false, 'create' => false, 'edit' => false, 'delete' => false, 'validate' => false, 'export' => false],
            'factures' => ['view' => false, 'create' => false, 'edit' => false, 'delete' => false, 'validate' => false, 'export' => false],
            'paiements' => ['view' => false, 'create' => false, 'edit' => false, 'delete' => false, 'validate' => false, 'export' => false],
            'stock' => ['view' => true, 'create' => false, 'edit' => true, 'delete' => false, 'validate' => false, 'export' => false],
            'fournisseurs' => ['view' => false, 'create' => false, 'edit' => false, 'delete' => false, 'validate' => false, 'export' => false],
            'bons_commande' => ['view' => false, 'create' => false, 'edit' => false, 'delete' => false, 'validate' => false, 'export' => false],
            'bons_livraison' => ['view' => true, 'create' => false, 'edit' => false, 'delete' => false, 'validate' => false, 'export' => false],
            'atelier' => ['view' => true, 'create' => true, 'edit' => true, 'delete' => false, 'validate' => true, 'export' => false],
            'rapports' => ['view' => false, 'create' => false, 'edit' => false, 'delete' => false, 'validate' => false, 'export' => false],
            'parametres' => ['view' => false, 'create' => false, 'edit' => false, 'delete' => false, 'validate' => false, 'export' => false],
            'utilisateurs' => ['view' => false, 'create' => false, 'edit' => false, 'delete' => false, 'validate' => false, 'export' => false],
            'abonnement' => ['view' => true, 'create' => true, 'edit' => false, 'delete' => false, 'validate' => false, 'export' => false],
        ],
        'user' => [
            'clients' => ['view' => true, 'create' => false, 'edit' => false, 'delete' => false, 'validate' => false, 'export' => false],
            'prescriptions' => ['view' => true, 'create' => false, 'edit' => false, 'delete' => false, 'validate' => false, 'export' => false],
            'ventes' => ['view' => false, 'create' => false, 'edit' => false, 'delete' => false, 'validate' => false, 'export' => false],
            'factures' => ['view' => false, 'create' => false, 'edit' => false, 'delete' => false, 'validate' => false, 'export' => false],
            'paiements' => ['view' => false, 'create' => false, 'edit' => false, 'delete' => false, 'validate' => false, 'export' => false],
            'stock' => ['view' => false, 'create' => false, 'edit' => false, 'delete' => false, 'validate' => false, 'export' => false],
            'fournisseurs' => ['view' => false, 'create' => false, 'edit' => false, 'delete' => false, 'validate' => false, 'export' => false],
            'bons_commande' => ['view' => false, 'create' => false, 'edit' => false, 'delete' => false, 'validate' => false, 'export' => false],
            'bons_livraison' => ['view' => false, 'create' => false, 'edit' => false, 'delete' => false, 'validate' => false, 'export' => false],
            'atelier' => ['view' => false, 'create' => false, 'edit' => false, 'delete' => false, 'validate' => false, 'export' => false],
            'rapports' => ['view' => false, 'create' => false, 'edit' => false, 'delete' => false, 'validate' => false, 'export' => false],
            'parametres' => ['view' => false, 'create' => false, 'edit' => false, 'delete' => false, 'validate' => false, 'export' => false],
            'utilisateurs' => ['view' => false, 'create' => false, 'edit' => false, 'delete' => false, 'validate' => false, 'export' => false],
            'abonnement' => ['view' => false, 'create' => false, 'edit' => false, 'delete' => false, 'validate' => false, 'export' => false],
        ],
    ],
];
